<Project>
  <PropertyGroup>
    <AnalysisLevel>latest</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CoreKitManagedPackageVersion>0.1.0-preview.1</CoreKitManagedPackageVersion>
  </PropertyGroup>
</Project>
